name: Test Docker Image

on:
  repository_dispatch:
    types: [test-docker-image]
  workflow_dispatch:

jobs:
  test-image-in-container:
    name: Test image in container
    runs-on: ubuntu-latest
    container: nevermendel/chrome-headless-screenshots:latest
    steps:
      - name: Generate screenshot
        run: take-screenshot.sh --outputDir=out https://github.com
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ContainerScreenshot
          path: out/screenshot.png
  test-image-in-vm:
    name: Test image in VM
    runs-on: ubuntu-latest
    steps:
      - name: Generate screenshot
        run: docker run -v ${pwd}:/usr/src/app/out --rm nevermendel/chrome-headless-screenshots:latest https://github.com
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: VMScreenshot
          path: screenshot.png
