name: Test and Publish Latest Docker Image

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: nevermendel/chrome-headless-screenshots:latest

      - name: Create temp directory
        run: mkdir -p temp

      - name: Test docker image
        working-directory: ./temp
        run: docker run -v ${PWD}:/usr/src/app/out --rm nevermendel/chrome-headless-screenshots https://github.com

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: screenshot
          path: ./temp/screenshot.png
          if-no-files-found: error

      - name: Push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' &&  github.ref == 'refs/heads/master' }}
          tags: nevermendel/chrome-headless-screenshots:latest